[tool.black]
line-length = 100

[tool.isort]
profile = "black"

[tool.pyright]
include = [
    "greenplumpython",
    "setup.py"
]
# FIXME: The lint error should be fixed for those files
ignore = [
    "*/table.py",
    "*/db.py",
    "*/expr.py"
]
