name: Doc 

on:
  push:
    branches:    
      - fix_path

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install apt dependencies
      run: sudo apt-get install -y libpq-dev
    - name: Set up Python 3.9 
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Set Variables
      id: set_variables
      run: |
        echo "::set-output name=PY::$(python -c 'import hashlib, sys;print(hashlib.sha256(sys.version.encode()+sys.executable.encode()).hexdigest())')"
        echo "::set-output name=PIP_CACHE::$(pip cache dir)"
    - name: Cache PIP
      uses: actions/cache@v2
      with:
        path: ${{ steps.set_variables.outputs.PIP_CACHE }}
        key: ubuntu-pip-${{ steps.set_variables.outputs.PY }}
    - name: Install dependencies
      run:  |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Make doc
      run: |
         sphinx-build -M html doc/source doc/build 

    # Publish built docs to gh-pages branch.
    # ===============================
    - name: Commit documentation changes
      run: |
        git clone https://github.com/yihong0618/GreenplumPython.git --branch gh-pages --single-branch gh-pages
        cp -r doc/build/html/* gh-pages/
        cd gh-pages
        touch .nojekyll
        git config --local user.email "zouzou0208@gmail.com"
        git config --local user.name "yihong0618"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # that.
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
