name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths-ignore:
      - "*.md"

jobs:
  build:
    name: python${{ matrix.python-version }}; ${{ matrix.server-version }}-${{ matrix.server-python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.9", "3.11"]
        server-base-image: ["postgres:12-bullseye", "postgres:12-bookworm"]
        include:
          - server-base-image: "postgres:12-bullseye"
            server-version: postgres12
            server-python-version: python39
          - server-base-image: "postgres:12-bookworm"
            server-version: postgres12
            server-python-version: python311
  
    steps:
    - uses: actions/checkout@v2
    - name: Setup python on client
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
    - name: Run tests without pickler
      run: |
        python3 -m pip install tox~=4.11 tox-docker~=4.1
        tox --override=docker:server.dockerfile=server/${{ matrix.server-version }}-${{ matrix.server-python-version }}.Dockerfile -e test-remote -- --override-ini=server_use_pickler=false
    - name: Run tests with pickler
      run: |
        tox --override=docker:server.dockerfile=server/${{ matrix.server-version }}-${{ matrix.server-python-version }}.Dockerfile -e test-remote -- --override-ini=server_use_pickler=true
