name: Test Postgres

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths-ignore:
      - "*.md"

jobs:
  build:
    name: Test client:python${{ matrix.python-version }}, server:postgres
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.9", "3.10"]
        postgres-image: ["12-bullseye", "12-bookworm"]
        include:
          - tox_test: "test_py39"
            python-version: "3.9"
          - tox_test: "test_py310"
            python-version: "3.10"
          - dill_version: python3.9
            postgres-version: '12'
          - dill_version: python3.9
            postgres-version: '13'

    services:
      postgres:
        image: postgres:${{ matrix.postgres-image }} 
        options: --name postgres-image-puller
  
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python ${{ matrix.python-version }} on client
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
    - name: Setup database server container
      run: |
        python3 -m pip install tox
        tox -e server
    - name: Run tests without pickler
      run: |
        tox -e ${{ matrix.tox_test }} 
    - name: Run tests with pickler
      run: |
        tox -e ${{ matrix.tox_test }} 
