name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths-ignore:
      - "*.md"

jobs:
  build:
    name: py${{ matrix.python-version }}; pg${{ matrix.postgres-version }}-py${{ matrix.postgres-python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.9", "3.11"]
        postgres-image: ["12-bullseye", "12-bookworm"]
        include:
          - postgres-image: "12-bullseye"
            postgres-version: 12
            postgres-python-version: 39
          - postgres-image: "12-bookworm"
            postgres-version: 12
            postgres-python-version: 311
  
    steps:
    - uses: actions/checkout@v2
    - name: Setup python on client
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
    - name: Setup database server
      run: |
        python3 -m pip install tox
        tox --override server.postgres_version=${{ matrix.postgres-version }} server.python_version=${{ matrix.postgres-python-version }} -e server
    - name: Run tests without pickler
      run: |
        tox --override client.python_version=${{ matrix.python-version }} -e test
    - name: Run tests with pickler
      run: |
        tox --override client.python_version=${{ matrix.python-version }} -e test
