name: Test Postgres

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths-ignore:
      - "*.md"

env:
  PGPASSWORD: postgres
  TESTDB: greenplum_python_test
  PGUSER: postgres

jobs:
  build:
    name: Test Python${{ matrix.python-version }}, PSQL${{matrix.postgres-version}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.9", "3.10"]
        python-server-version: ["39", "311"]
        postgres-version: ["12-bullseye", "12-bookworm"]
        include:
          - tox_test: "test_py39"
            python-version: "3.9"
          - tox_test: "test_py310"
            python-version: "3.10"
          - dill_version: python3.9
            postgres-version: '12'
          - dill_version: python3.9
            postgres-version: '13'

    services:
      postgres:
        image: postgres:${{ matrix.postgres-version }} 
        options: --name postgres-image-puller
  
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
  
    - name: Setup database server container
      run: |
        python3 -m pip install tox
        tox -e server

    - name: Run Tests
      run: |
        export POSTGRES_PASSWORD=${{ env.PGPASSWORD }}
        export POSTGRES_USER=${{ env.PGUSER }}
        export POSTGRES_DB=${{ env.TESTDB }}
        tox -e ${{ matrix.tox_test }} 

    - name: Install Dependencies for greenplumpython dill
      # plpytyhon for postgres install to pg services
      run: |
          pip install pip install --target=. dill
          docker cp dill $(docker ps -q):/usr/lib/${{ matrix.dill_version }}/
          rm -rf dill pip
    - name: Run Tests with dill
      run: |
        export POSTGRES_PASSWORD=${{ env.PGPASSWORD }}
        export POSTGRES_USER=${{ env.PGUSER }}
        export POSTGRES_DB=${{ env.TESTDB }}
        tox -e ${{ matrix.tox_test }} 
