name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths-ignore:
      - "*.md"

jobs:
  build:
    name: python${{ matrix.python-version }}; ${{ matrix.server }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.9", "3.11"]
        server: ["postgres12-python39", "postgres12-python311"]
        include:
          - server: "postgres12-python39"
            server-python-version: "3.9"
          - server: "postgres12-python311"
            server-python-version: "3.11"
  
    steps:
    - uses: actions/checkout@v2
    - name: Setup python on client
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
    - name: Build server image
      run: |
        docker build \
          -t greenplumpython-server:{{ matrix.server }} \
          -f server/{{ matrix.server }}.Dockerfile server
    - name: Run tests without pickler
      run: |
        python3 -m pip install tox~=4.11 tox-docker~=4.1 && \
        tox \
          --override=docker:server.image=greenplumpython-server:{{ matrix.server }} \
          -e test-container \
          -- \
          --override-ini=server_use_pickler=false \
          --ignore=tests/test_use_pickler.py \
    - name: Run tests with pickler if python versions match
      if: ${{ matrix.python-version == matrix.server-python-version }}
      run: |
        tox \
          --override=docker:server.image=greenplumpython-server:{{ matrix.server }} \
          -e test-container \
          -- \
          --override-ini=server_use_pickler=true \
