name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths-ignore:
      - "*.md"

jobs:
  build:
    name: python${{ matrix.python-version }}; ${{ matrix.server-version }}-${{ matrix.server-python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.9", "3.11"]
        postgres-image: ["12-bullseye", "12-bookworm"]
        include:
          - postgres-image: "12-bullseye"
            server-version: postgres12
            server-python-version: python39
          - postgres-image: "12-bookworm"
            server-version: postgres12
            server-python-version: python311
  
    steps:
    - uses: actions/checkout@v2
    - name: Setup python on client
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
    - name: Setup database server
      run: |
        python3 -m pip install tox
        tox --override server.version=${{ matrix.server-version }} --override server.python_version=${{ matrix.server-python-version }} -e server
    - name: Run tests without pickler
      run: |
        tox --override client.python_version=${{ matrix.python-version }} -e test
    - name: Run tests with pickler
      run: |
        tox --override client.python_version=${{ matrix.python-version }} -e test
